name: javaCodesWorkflow
on: [workflow_dispatch, push]
jobs:
  runHelloWorld:
    runs-on: windows-latest
    steps:
      - name: Download File onto Github Server
        uses: actions/checkout@v6.1.0
      - name: Setup Java On Github Server
        uses: actions/setup-java@v6.0.1
        with:
          java-version: 21
          distribution: temurin
      - name: Run The Hello World Function to Create Class File
        run: javac JavaCodes/PrintingHelloWorld.java
      - name: Run the .class File
        run: java -cp JavaCodes PrintingHelloWorld
  
  runLifeTruth:
    needs: runHelloWorld
    runs-on: windows-latest
    steps:
      - name: Download File onto Github Server
        uses: actions/checkout@v6.1.0
      - name: Setup Java On Github Server
        uses: actions/setup-java@v6.0.1
        with:
          java-version: 21
          distribution: temurin
      - name: Run The Life Truth Function to Create Class File
        run: javac JavaCodes/PrintLifeTruth.java
      - name: Run the .class File
        run: java -cp JavaCodes PrintLifeTruth
        
    
